// Copied from PIHPS on 2026-10-08:
// https://www.bi.go.id/hargapangan/WebSite/TabelHarga/GetRefProvince
// https://www.bi.go.id/hargapangan/WebSite/TabelHarga/GetRefCommodityAndCategory
// Names are trimmed; PIHPS sends "Cabai Merah Keriting " with a trailing space. Every price is per kg.
export const provinces = [
  { id: 1, name: "Aceh" },
  { id: 2, name: "Sumatera Utara" },
  { id: 3, name: "Sumatera Barat" },
  { id: 4, name: "Riau" },
  { id: 5, name: "Kepulauan Riau" },
  { id: 6, name: "Jambi" },
  { id: 7, name: "Bengkulu" },
  { id: 8, name: "Sumatera Selatan" },
  { id: 9, name: "Kepulauan Bangka Belitung" },
  { id: 10, name: "Lampung" },
  { id: 11, name: "Banten" },
  { id: 12, name: "Jawa Barat" },
  { id: 13, name: "DKI Jakarta" },
  { id: 14, name: "Jawa Tengah" },
  { id: 15, name: "DI Yogyakarta" },
  { id: 16, name: "Jawa Timur" },
  { id: 17, name: "Bali" },
  { id: 18, name: "Nusa Tenggara Barat" },
  { id: 19, name: "Nusa Tenggara Timur" },
  { id: 20, name: "Kalimantan Barat" },
  { id: 21, name: "Kalimantan Selatan" },
  { id: 22, name: "Kalimantan Tengah" },
  { id: 23, name: "Kalimantan Timur" },
  { id: 24, name: "Kalimantan Utara" },
  { id: 25, name: "Gorontalo" },
  { id: 26, name: "Sulawesi Selatan" },
  { id: 27, name: "Sulawesi Tenggara" },
  { id: 28, name: "Sulawesi Tengah" },
  { id: 29, name: "Sulawesi Utara" },
  { id: 30, name: "Sulawesi Barat" },
  { id: 31, name: "Maluku" },
  { id: 32, name: "Maluku Utara" },
  { id: 33, name: "Papua" },
  { id: 34, name: "Papua Barat" },
] as const;

export const categories = [
  { id: "cat_1", name: "Beras" },
  { id: "cat_2", name: "Daging Ayam" },
  { id: "cat_3", name: "Daging Sapi" },
  { id: "cat_4", name: "Telur Ayam" },
  { id: "cat_5", name: "Bawang Merah" },
  { id: "cat_6", name: "Bawang Putih" },
  { id: "cat_7", name: "Cabai Merah" },
  { id: "cat_8", name: "Cabai Rawit" },
  { id: "cat_9", name: "Minyak Goreng" },
  { id: "cat_10", name: "Gula Pasir" },
] as const;

export const variants = [
  { id: "com_1", name: "Beras Kualitas Bawah I", categoryId: "cat_1" },
  { id: "com_2", name: "Beras Kualitas Bawah II", categoryId: "cat_1" },
  { id: "com_3", name: "Beras Kualitas Medium I", categoryId: "cat_1" },
  { id: "com_4", name: "Beras Kualitas Medium II", categoryId: "cat_1" },
  { id: "com_5", name: "Beras Kualitas Super I", categoryId: "cat_1" },
  { id: "com_6", name: "Beras Kualitas Super II", categoryId: "cat_1" },
  { id: "com_7", name: "Daging Ayam Ras Segar", categoryId: "cat_2" },
  { id: "com_8", name: "Daging Sapi Kualitas 1", categoryId: "cat_3" },
  { id: "com_9", name: "Daging Sapi Kualitas 2", categoryId: "cat_3" },
  { id: "com_10", name: "Telur Ayam Ras Segar", categoryId: "cat_4" },
  { id: "com_11", name: "Bawang Merah Ukuran Sedang", categoryId: "cat_5" },
  { id: "com_12", name: "Bawang Putih Ukuran Sedang", categoryId: "cat_6" },
  { id: "com_13", name: "Cabai Merah Besar", categoryId: "cat_7" },
  { id: "com_14", name: "Cabai Merah Keriting", categoryId: "cat_7" },
  { id: "com_15", name: "Cabai Rawit Hijau", categoryId: "cat_8" },
  { id: "com_16", name: "Cabai Rawit Merah", categoryId: "cat_8" },
  { id: "com_17", name: "Minyak Goreng Curah", categoryId: "cat_9" },
  { id: "com_18", name: "Minyak Goreng Kemasan Bermerk 1", categoryId: "cat_9" },
  { id: "com_19", name: "Minyak Goreng Kemasan Bermerk 2", categoryId: "cat_9" },
  { id: "com_20", name: "Gula Pasir Kualitas Premium", categoryId: "cat_10" },
  { id: "com_21", name: "Gula Pasir Lokal", categoryId: "cat_10" },
] as const;
